import Link from "next/link";

const releaseUrl = process.env.NEXT_PUBLIC_ASTRA_DOWNLOAD_URL ?? "#download";
function Mark() { return <span className="astra-mark" aria-hidden="true"><i /><i /><i /></span>; }

export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Main navigation"><Link className="brand" href="/"><Mark />ASTRA</Link><div className="nav-links"><a href="#demo">Demo</a><Link href="/docs">Documentation</Link><Link href="/policies">Policies</Link></div><a className="button button-small" href={releaseUrl}>Download <span>↗</span></a></nav>
    <section className="hero shell"><div className="hero-copy"><p className="eyebrow"><span className="live-dot" /> WINDOWS DESKTOP DIAGNOSTICS</p><h1>Know what your PC needs.<br /><em>Before you change it.</em></h1><p className="lede">Astra turns plain-language questions into clear, local system diagnostics—so you can understand your Windows PC without digging through settings.</p><div className="hero-actions"><a className="button" href={releaseUrl}>Download for Windows <span>↓</span></a><a className="text-link" href="#demo">See how it works <span>↓</span></a></div><p className="microcopy">Windows 10/11 · Local diagnostics · Your choice of AI provider</p></div>
      <div className="app-frame" aria-label="Astra application preview"><div className="window-bar"><span className="window-name"><Mark /> ASTRA</span><span>— &nbsp; □ &nbsp; ×</span></div><div className="app-body"><aside><p>OVERVIEW</p><b>Conversation</b><b>System status</b><b>Settings</b><div className="system-state"><span className="live-dot" /> SYSTEM READY</div></aside><div className="conversation"><div className="status-line"><span>LOCAL SESSION</span><span>OLLAMA · CONNECTED</span></div><p className="question">Why is my laptop running slowly?</p><div className="answer"><span className="agent-dot">A</span><p>I found two likely causes: memory usage is high and several startup apps are running in the background.</p></div><div className="diagnostic"><div><small>MEMORY</small><strong>82%</strong></div><div className="meter"><i /></div><span>HIGH</span></div><div className="composer">Ask about your system <kbd>↵</kbd></div></div></div></div>
    </section>
    <section id="demo" className="demo-section"><div className="shell section-heading"><p className="eyebrow">HOW ASTRA WORKS</p><h2>Plain questions.<br />Useful answers.</h2><p>Astra gathers the relevant local information, explains what it found, and keeps you in control of what happens next.</p></div><div className="shell flow"><article><span className="step">01</span><h3>Ask naturally</h3><p>“Why is my battery draining?” “What is using all my memory?” “Is Windows up to date?”</p></article><article><span className="step">02</span><h3>Inspect locally</h3><p>Astra uses focused, read-only checks to understand your system—not guess at it.</p></article><article><span className="step">03</span><h3>Decide with context</h3><p>Get a clear answer, supporting details, and a record of what Astra checked.</p></article></div></section>
    <section className="shell trust-section"><div><p className="eyebrow amber">CONTROL IS A FEATURE</p><h2>Helpful, not presumptuous.</h2></div><div className="trust-copy"><p>Astra is built around local, read-only diagnostics. It checks your PC to answer your question; it does not make changes on its own.</p><Link className="text-link" href="/policies">Read our policies <span>→</span></Link></div></section>
    <section id="download" className="shell download-section"><div><Mark /><p className="eyebrow">GET STARTED</p><h2>See your system<br />more clearly.</h2></div><div><a className="button" href={releaseUrl}>Download Astra for Windows <span>↓</span></a><p className="microcopy">Astra 1.0.0 · Windows x64</p></div></section>
    <footer className="shell"><Link className="brand" href="/"><Mark />ASTRA</Link><div><Link href="/docs">Documentation</Link><Link href="/policies">Privacy & policies</Link></div><p>© {new Date().getFullYear()} Astra</p></footer>
  </main>;
}
